Failed to load resource: the server responded with a status of 400 ()Understand this error page.tsx:980 Recording payment. Payload: {   "fromUserId": "WHEtiIf0OZdrfIfwN2yGc0B0ReE3",   "toUserId": "nFwfgL28iJT5nCDVPaPAHnya7jg2",   "amount": 3666.666666666667,   "currency": "INR",   "dateRecorded": {     "_methodName": "serverTimestamp"   },   "recordedBy": "dGdKM1ywlCWYp8LfGL10SYOZfDa2",   "notes": "" } page.tsx:981 Using trip.baseCurrency from client trip object: INR page.tsx:991 Error recording payment: FirebaseError: Missing or insufficient permissions.
i think this is a problem with the db
Something is not created in the db

Pls resolve the issue